receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      label1: hello-service
  
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
    
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  otlp/jaeger:
    endpoint: http://jaeger-all-in-one:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, otlp/jaeger, logging, otlp]

